### ISSUE TITLE
Writer functionality

### ISSUE THREAD

**Issue by Congyuwang** [michel-kraemer/actson-rs#36]
This is a wonderful crate, and very solidly implemented (IMO).

Does this crate have streaming serialization functionality? (i.e., calling `begin_object()` `end_object()` and etc, while the writer writes to a `io::Write` object), or even better, asynchronously (`begin_object().await`) and so on.

**Comment by michel-kraemer** [comment]
Sorry, but actson-rs is a JSON parser only. It is not possible to write JSON documents.
