### ISSUE TITLE
AsyncStream is closed with streaming mode active

### ISSUE THREAD

**Issue by sandercm** [michel-kraemer/actson-rs#37]
Hi I noticed that the parser would stop parsing more json thinking it reached the end of the file.

My code is using the example 
```
        let feeder = AsyncBufReaderJsonFeeder::new(BufReader::new(reader));
        let parser = JsonParser::new_with_options(
            feeder,
            JsonParserOptionsBuilder::default()
                .with_streaming(true) // this enables our weird json stream usecase
                .build(),
        );
```

My use case is listening on a UDS for json events to come in, but currently it seems to shutdown the parser after receiving a full message. I suspect because the BufReader is empty waiting for more data. I fixed the issue by adding the following `&& self.streaming == false` in the parser.rs file.

I don't know if this is the correct approach to fixing this issue?

in parser.rs : 339
`if self.feeder.is_done()` -> `if self.feeder.is_done() && self.streaming == false`

**Comment by michel-kraemer** [comment]
I tried to write a test that reproduces this issue but did not succeed.

```rust
#[tokio::test]
async fn parse_from_stream() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("parse_from_stream");
    let (tx, mut rx) = mpsc::unbounded_channel();

    let t = tokio::spawn(async move {
        let listener = UnixListener::bind(&path).unwrap();
        tx.send(path.to_string_lossy().to_string()).unwrap();

        if let Ok((socket, _)) = listener.accept().await {
            let reader = BufReader::new(socket);
            let feeder = AsyncBufReaderJsonFeeder::new(reader);
            let mut parser = JsonParser::new_with_options(
                feeder,
                JsonParserOptionsBuilder::default()
                    .with_streaming(true)
                    .build(),
            );
            let mut prettyprinter = PrettyPrinter::new();

            while let Some(e) = parser.next_event().unwrap() {
                if e == JsonEvent::NeedMoreInput {
                    parser.feeder.fill_buf().await.unwrap();
                }
                prettyprinter.on_event(e, &parser).unwrap();
                if e == JsonEvent::EndObject {
                    tx.send(prettyprinter.get_result().to_string()).unwrap();
                    prettyprinter = PrettyPrinter::new();
                }
            }
        }
    });

    let path = rx.recv().await.unwrap();
    let mut client = UnixStream::connect(path).await.unwrap();

    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;

    client.write_all(br#"{"name"#).await.unwrap();

    tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;

    client.write_all(br#"": "Elvis"}"#).await.unwrap();

    let pretty_obj = rx.recv().await.unwrap();
    println!("{}", pretty_obj);

    client.write_all(br#"{"name": "Max"}"#).await.unwrap();

    let pretty_obj2 = rx.recv().await.unwrap();
    println!("{}", pretty_obj2);

    drop(client);

    t.await.unwrap();
}
```

Can you elaborate on the difference between your code and this test? Maybe you can provide a reproducer that demonstrates your issue? This would help a lot. Thanks!

**Comment by michel-kraemer** [comment]
The problem is not the parser but the feeder. `AsyncBufReaderJsonFeeder#isDone()` returns true as soon as the underlying `BufReader` has reached the end of file, which is *usually* indicated by returning an empty buffer. I guess in your case, your stream can return an empty buffer even though more data will follow.

The easiest way to deal with this is to implement a custom `JsonFeeder` whose `isDone()` method never returns `true`. You could even write a small wrapper like so:

```rust
pub struct StreamingFeeder<T>
where
    T: AsyncRead + Unpin,
{
    delegate: AsyncBufReaderJsonFeeder<T>,
}

impl<T> StreamingFeeder<T>
where
    T: AsyncRead + Unpin,
{
    pub fn new(delegate: AsyncBufReaderJsonFeeder<T>) -> Self {
        StreamingFeeder { delegate }
    }

    pub async fn fill_buf(&mut self) -> Result<(), FillError> {
        self.delegate.fill_buf().await
    }
}

impl<T> JsonFeeder for StreamingFeeder<T>
where
    T: AsyncRead + Unpin,
{
    fn has_input(&self) -> bool {
        self.delegate.has_input()
    }

    fn is_done(&self) -> bool {
        // THIS FEEDER IS NEVER DONE!
        false
    }

    fn next_input(&mut self) -> Option<u8> {
        self.delegate.next_input()
    }
}
```

**Comment by sandercm** [comment]
> The problem is not the parser but the feeder. `AsyncBufReaderJsonFeeder#isDone()` returns true as soon as the underlying `BufReader` has reached the end of file, which is _usually_ indicated by returning an empty buffer. I guess in your case, your stream can return an empty buffer even though more data will follow.
> 
> The easiest way to deal with this is to implement a custom `JsonFeeder` whose `isDone()` method never returns `true`. You could even write a small wrapper like so:
> 
> ```rust
> pub struct StreamingFeeder<T>
> where
>     T: AsyncRead + Unpin,
> {
>     delegate: AsyncBufReaderJsonFeeder<T>,
> }
> 
> impl<T> StreamingFeeder<T>
> where
>     T: AsyncRead + Unpin,
> {
>     pub fn new(delegate: AsyncBufReaderJsonFeeder<T>) -> Self {
>         StreamingFeeder { delegate }
>     }
> 
>     pub async fn fill_buf(&mut self) -> Result<(), FillError> {
>         self.delegate.fill_buf().await
>     }
> }
> 
> impl<T> JsonFeeder for StreamingFeeder<T>
> where
>     T: AsyncRead + Unpin,
> {
>     fn has_input(&self) -> bool {
>         self.delegate.has_input()
>     }
> 
>     fn is_done(&self) -> bool {
>         // THIS FEEDER IS NEVER DONE!
>         false
>     }
> 
>     fn next_input(&mut self) -> Option<u8> {
>         self.delegate.next_input()
>     }
> }
> ```

ill try this out thanks

**Comment by michel-kraemer** [comment]
I appreciate your offer, but I'm not sure if including such a feeder wouldn't confuse people more than it would help. The term *streaming* is ambiguous: Actson understands it as reading multiple JSON documents from a stream without keeping the whole data in memory. However, the stream is expected to end eventually. In your case, *streaming* means waiting for data to arrive, parsing it, and then waiting for more data. Your stream is infinite. This requires, in my opinion, a custom (i.e. specific to your use case) feeder implementation.

Having said that, if other people reading this in the future have similar requirements, don't hesitate to comment here!
