### ISSUE TITLE
Ownership of Feeder in the context of JsonParser

### ISSUE THREAD

**Issue by BernhardLThomas** [michel-kraemer/actson-rs#4]
# Issue

`JsonParser` taking a reference to `Feeder` makes it difficult to write abstractions that contain both the parser and the feeder, as this would cause the struct to be self referential. This brings difficulties in Rust. 

# Proposals

## Proposal 1: Own `Feeder`

`JsonParser` should either take ownership of  `Feeder`, either through exclusive ownership or through shared ownership (`Arc`). 

## Proposal 2: Provide feeder at call site of `next_event(..)`

`JsonParser` should not own, or have a reference to, a `Feeder`. Instead the dependency can be provided when `JsonParser::next_event(...)` is called. This has the additional benefit of making the `JsonParser` non-generic, merely the `next_event(..)` method needs to be generic over `Feeder`. 

# Pull Request

Proposal 2 has been implemented and a pull request will be made.

# Related issues

`BufReaderJsonFeeder` and `AsyncBufReaderJsonFeeder` have a similar issue, in that they contain an exclusive reference to a `BufReader`, instead of taking ownership.

**Comment by michel-kraemer** [comment]
Thanks for the proposals. I've just pushed a commit that implements the first proposal. As discussed in person, the second one will not be implemented.
